### PR TITLE
Provide issue templates, add CODEOWNERS & license, basic README 

### PR DESCRIPTION
**Pull request by tomkerkhove**

### CODE REVIEW

**Comment by tomkerkhove** [comment]
This is odd. Is this because you are testing @stijnmoreels? 🤔

**Comment by stijnmoreels** [comment]
Hmm, no. Not that I know of?

**Comment by tomkerkhove** [comment]
It looks like something is pushing packages such as https://www.myget.org/feed/arcus/package/nuget/Arcus.WebApi.All/1.0.0 for all our projects.

Maybe there is a bug in our MyGet YAML?

**Comment by tomkerkhove** [comment]
Our bot is using the version to determine the issue/PR to comment to, in this case 1.0.0 resolves to PR 1

**Comment by tomkerkhove** [comment]
Found the issue, commented on your PRs.

**Pull request merged**
