### PR TITLE
Provide capability to push raw events

### LINKED ISSUE #57: Provide capability to push a raw event
As of today, we only support pushing events with a typed schema.

We should also provide the capability to push events without a schema based on a raw JSON string.

## Syntax Proposal
```csharp
string licensePlate = "1-TOM-337";
string eventSubject = $"/cars/{licensePlate}";
string eventId = Guid.NewGuid().ToString();
string rawEventPayload = $"{{ \"licensePlate\": \"{licensePlate}\"}}";

await eventGridPublisher.Publish(eventId, eventSubject, rawEventPayload);
```

## Task List
- [X] Implementation
- [ ] Documentation

### PR DESCRIPTION
**Pull request by tomkerkhove**
Provide capability to push raw events.

Closes #57

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Interpretation of EventType & DataVersion are not working as it should, will fix it and provide tests

**Comment by tomkerkhove** [comment]
This is done but I've created #66 	as this is not ideal.

Feel free to let me know what you think @SamVanhoutte 	& @stijnmoreels

**Comment by stijnmoreels** [comment]
Sorry @tomkerkhove for the review delay. It's almost February! 😊

**Comment by tomkerkhove** [comment]
Not sure if I'm following, what does February have to do with that? :)

**Comment by tomkerkhove** [comment]
Given I need this for https://github.com/arcus-azure/arcus.eventgrid.sidecar/pull/29 and it works + nothing breaking I'll merge this in but feel free to do review this and I'll do a follow-up PR

**Pull request merged**
