### PR TITLE
Use CloudEvents 1.0 as input schema for integration testing (ARM template)

### LINKED ISSUE #115: Change Event Grid topic to use CloudEvents as input in ARM template
Change Event Grid topic to use CloudEvents as input in ARM template instead of homegrown format.

### PR DESCRIPTION
**Pull request by tomkerkhove**
Closes #115

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Let's wait until #117 is finished.

**Comment by tomkerkhove** [comment]
This should be good to go now that #119 is merged and uses CloudEvents for integration tests as well.

**Comment by stijnmoreels** [comment]
> This should be good to go now that #119 is merged and uses CloudEvents for integration tests as well.

Should we then provide both with and without cloudevents?

**Comment by tomkerkhove** [comment]
This is for https://eventgrid.arcus-azure.net/features/running-integration-tests, not our internal testing landscape

**Pull request merged**
